package space.worldengine.client;

import android.app.Activity;
import android.app.DownloadManager;
import android.content.Intent;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.Environment;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.*;
import android.widget.*;
import org.json.*;
import java.net.URL;
import java.util.concurrent.Executors;

/** Native library and navigation; web engines run in a separate, persistent game surface. */
public final class MainActivity extends Activity {
 private final java.util.concurrent.ExecutorService network=Executors.newFixedThreadPool(3);
 private WebView game; private FrameLayout surface; private LinearLayout root,toolbar; private TextView heading; private JSONArray catalog=new JSONArray();
 private View fullScreen; private WebChromeClient.CustomViewCallback fullScreenCallback; private ValueCallback<Uri[]> fileCallback;
 private String networkAgent="Mozilla/5.0 WorldEngineClientAndroid/1.0"; private boolean ready=false,playing=false,catalogLoading=false; private android.net.ConnectivityManager connectivity; private android.net.ConnectivityManager.NetworkCallback networkCallback; private String current=null,pending=null; private View library;
 private static final int BG=0xff050607,PANEL=0xff0d1115,GOLD=0xffe5f4fa,TEXT=0xffe7e9ea;
 private static final String HOME="https://worldengine.space/play/";
 private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density);}
 private static boolean internal(Uri u){String p=u.getPath();return "https".equals(u.getScheme())&&"worldengine.space".equals(u.getHost())&&p!=null&&(p.equals("/play")||p.startsWith("/play/"));}
 private void external(String url){try{if("https".equals(Uri.parse(url).getScheme()))startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(android.content.ActivityNotFoundException ignored){}}
 private TextView text(String value,int size,int color){TextView v=new TextView(this);v.setText(value);v.setTextSize(size);v.setTextColor(color);return v;}
 private Button button(String title,Runnable click){Button b=new Button(this);b.setText(title);b.setTextColor(GOLD);b.setTextSize(11);b.setAllCaps(false);b.setPadding(dp(7),0,dp(7),0);b.setMinWidth(0);b.setMinimumWidth(0);b.setBackgroundColor(PANEL);b.setOnClickListener(v->click.run());return b;}
 private void attach(View view){surface.removeAllViews();if(view.getParent()!=null)((ViewGroup)view.getParent()).removeView(view);surface.addView(view,new FrameLayout.LayoutParams(-1,-1));}
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(BG);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});toolbar=new LinearLayout(this);toolbar.setGravity(android.view.Gravity.CENTER_VERTICAL);toolbar.setBackgroundColor(PANEL);root.addView(toolbar,new LinearLayout.LayoutParams(-1,dp(48)));surface=new FrameLayout(this);root.addView(surface,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
 game=new WebView(this);game.setBackgroundColor(BG);WebView.setWebContentsDebuggingEnabled(getIntent().getBooleanExtra("smokeTest",false));WebSettings settings=game.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(true);settings.setMediaPlaybackRequiresUserGesture(false);settings.setUserAgentString(settings.getUserAgentString()+" WorldEngineClientAndroid/1.0");networkAgent=settings.getUserAgentString();CookieManager.getInstance().setAcceptCookie(true);
 game.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView view,WebResourceRequest request){if(!request.isForMainFrame()||internal(request.getUrl()))return false;external(request.getUrl().toString());return true;}
 @Override public void onPageFinished(WebView view,String url){if(internal(Uri.parse(url)))checkReady(0);}
 @Override public void onReceivedError(WebView view,WebResourceRequest request,WebResourceError error){if(!request.isForMainFrame())return;ready=false;if(playing){Toast.makeText(MainActivity.this,"Connect to the internet to play. Your library is still available.",Toast.LENGTH_LONG).show();showLibrary();}}});
 game.setWebChromeClient(new WebChromeClient(){@Override public void onShowCustomView(View view,CustomViewCallback callback){fullScreen=view;fullScreenCallback=callback;setContentView(view);}@Override public void onHideCustomView(){if(fullScreen==null)return;fullScreen=null;setContentView(root);fullScreenCallback.onCustomViewHidden();fullScreenCallback=null;}
 @Override public boolean onShowFileChooser(WebView view,ValueCallback<Uri[]> callback,FileChooserParams params){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=callback;try{startActivityForResult(params.createIntent(),41);return true;}catch(android.content.ActivityNotFoundException error){fileCallback=null;return false;}}});
 game.setDownloadListener((url,agent,disposition,mime,length)->external(url));game.loadUrl(HOME);showLoading();loadCatalog();
 connectivity=(android.net.ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);networkCallback=new android.net.ConnectivityManager.NetworkCallback(){@Override public void onCapabilitiesChanged(android.net.Network available,android.net.NetworkCapabilities capabilities){if(capabilities.hasCapability(android.net.NetworkCapabilities.NET_CAPABILITY_VALIDATED))runOnUiThread(()->{if(isFinishing()||isDestroyed())return;if(catalog.length()==0)loadCatalog();if(!ready)game.loadUrl(HOME);});}};connectivity.registerDefaultNetworkCallback(networkCallback);
 game.postDelayed(()->{if(catalog.length()==0)loadCatalog();},5000);game.postDelayed(()->{if(catalog.length()==0)loadCatalog();},15000);
 }
 private void checkReady(int count){game.evaluateJavascript("Boolean(window.WorldEngineClient?.ready())",value->{if("true".equals(value)){ready=true;if(pending!=null){String action=pending;pending=null;engine(action);}}else if(count<100)game.postDelayed(()->checkReady(count+1),200);});}
 private void engine(String action){if(!ready){pending=action;game.loadUrl(HOME);return;}game.evaluateJavascript(action,null);}
 private void nav(){toolbar.removeAllViews();toolbar.addView(button("▦ Library",()->{engine("window.WorldEngineClient.save()");showLibrary();}));heading=text(playing?"Playing":"WORLD ENGINE",11,TEXT);heading.setSingleLine(true);heading.setEllipsize(android.text.TextUtils.TruncateAt.END);heading.setPadding(dp(10),0,0,0);toolbar.addView(heading,new LinearLayout.LayoutParams(0,-2,1));if(current!=null)toolbar.addView(button("▶ Resume",()->{playing=true;attach(game);nav();}));if(!playing)toolbar.addView(button("☆",()->{playing=true;attach(game);nav();engine("window.WorldEngineClient.wishlist()");}));toolbar.addView(button("◎ Account",()->{playing=true;attach(game);nav();engine("window.WorldEngineClient.account()");}));}
 private void showLoading(){nav();TextView loading=text("Loading your library…",18,TEXT);loading.setGravity(android.view.Gravity.CENTER);attach(loading);}
 private java.io.InputStream open(String url) throws java.io.IOException {java.net.URLConnection connection=new URL(url).openConnection();connection.setRequestProperty("User-Agent",networkAgent);connection.setConnectTimeout(20000);connection.setReadTimeout(20000);return connection.getInputStream();}
 private String readText(java.io.InputStream stream) throws java.io.IOException {java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[8192];int count;while((count=stream.read(buffer))!=-1)bytes.write(buffer,0,count);return bytes.toString("UTF-8");}
 private void loadCatalog(){if(isFinishing()||isDestroyed()||catalogLoading)return;catalogLoading=true;network.execute(()->{try{String data;try(java.io.InputStream input=open("https://worldengine.pages.dev/play/games.json")){data=readText(input);}JSONArray result=new JSONArray(data);getPreferences(0).edit().putString("catalog",data).apply();runOnUiThread(()->{if(isFinishing()||isDestroyed())return;catalogLoading=false;catalog=result;if(!playing)showLibrary();});}catch(Exception e){android.util.Log.w("WorldEngine","Catalog fetch failed: "+e.getClass().getSimpleName()+": "+e.getMessage());try{catalog=new JSONArray(getPreferences(0).getString("catalog","[]"));}catch(Exception ignored){}runOnUiThread(()->{if(isFinishing()||isDestroyed())return;catalogLoading=false;if(!playing)showLibrary();});}});}
 private void showLibrary(){playing=false;nav();LinearLayout content=new LinearLayout(this);content.setOrientation(1);content.setPadding(dp(14),dp(12),dp(14),dp(12));TextView title=text("Library",24,TEXT);title.setTypeface(null,Typeface.BOLD);content.addView(title);TextView subtitle=text(catalog.length()+" games · Tap to play",11,0xff8999aa);LinearLayout.LayoutParams sub=new LinearLayout.LayoutParams(-1,-2);sub.bottomMargin=dp(12);content.addView(subtitle,sub);if(catalog.length()==0){subtitle.setText("Connect to load your games.");content.addView(button("Retry",()->{showLoading();loadCatalog();game.loadUrl(HOME);}));}
 int columns=getResources().getConfiguration().orientation==2?5:2;int rows=(catalog.length()+columns-1)/columns;LinearLayout grid=new LinearLayout(this);grid.setOrientation(1);content.addView(grid,new LinearLayout.LayoutParams(-1,0,1));for(int row=0;row<rows;row++){LinearLayout line=new LinearLayout(this);grid.addView(line,new LinearLayout.LayoutParams(-1,0,1));for(int col=0;col<columns;col++){int index=row*columns+col;if(index>=catalog.length())break;JSONObject item=catalog.optJSONObject(index);if(item==null)continue;LinearLayout card=new LinearLayout(this);card.setOrientation(1);GradientDrawable background=new GradientDrawable();background.setColor(PANEL);background.setCornerRadius(0);background.setStroke(dp(1),0xff34414f);card.setBackground(background);card.setClipToOutline(true);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-1,1);cp.setMargins(dp(4),dp(4),dp(4),dp(4));line.addView(card,cp);ImageView art=new ImageView(this);art.setScaleType(ImageView.ScaleType.CENTER_CROP);card.addView(art,new LinearLayout.LayoutParams(-1,0,1));TextView label=text(item.optString("title"),11,TEXT);label.setMaxLines(2);label.setPadding(dp(8),dp(6),dp(8),dp(6));card.addView(label);card.setContentDescription(item.optString("title"));card.setFocusable(true);card.setOnClickListener(v->launch(item));card.setOnLongClickListener(v->{download(item);return true;});String image=item.optString("image");if(image.startsWith("/play/media/"))network.execute(()->{try(java.io.InputStream stream=open("https://worldengine.pages.dev"+image)){android.graphics.Bitmap bitmap=android.graphics.BitmapFactory.decodeStream(stream);runOnUiThread(()->art.setImageBitmap(bitmap));}catch(Exception ignored){}});}}
 TextView hint=text("Hold a game to download its standalone edition.",10,0xff8999aa);hint.setPadding(0,dp(10),0,0);content.addView(hint);library=content;attach(content);}
 private void launch(JSONObject item){current=item.optString("id");playing=true;attach(game);nav();engine("window.WorldEngineClient.launch("+JSONObject.quote(current)+")");}
 private void download(JSONObject item){JSONObject assets=item.optJSONObject("downloads"),asset=assets==null?null:assets.optJSONObject("android");if(asset==null)return;String url=asset.optString("url"),filename=asset.optString("filename");if(!url.startsWith("https://github.com/worldengine-space/game-downloads/releases/download/")||!filename.matches("[a-zA-Z0-9._-]+"))return;new android.app.AlertDialog.Builder(this).setTitle(item.optString("title")).setMessage("Download standalone Android edition ("+Math.round(asset.optDouble("bytes")/1048576)+" MB)?").setNegativeButton("Cancel",null).setPositiveButton("Download",(d,w)->{if(android.os.Build.VERSION.SDK_INT<29){external(url);return;}DownloadManager.Request request=new DownloadManager.Request(Uri.parse(url)).setTitle(item.optString("title")).setNotificationVisibility(DownloadManager.Request.VISIBILITY_VISIBLE_NOTIFY_COMPLETED).setDestinationInExternalPublicDir(Environment.DIRECTORY_DOWNLOADS,filename);((DownloadManager)getSystemService(DOWNLOAD_SERVICE)).enqueue(request);Toast.makeText(this,"Downloading. Open Downloads when complete to install.",Toast.LENGTH_LONG).show();}).show();}
 @Override public void onConfigurationChanged(android.content.res.Configuration config){super.onConfigurationChanged(config);if(!playing)showLibrary();}
 @Override public void onBackPressed(){if(fullScreen!=null){game.getWebChromeClient().onHideCustomView();return;}if(playing){engine("window.WorldEngineClient.save()");showLibrary();}else super.onBackPressed();}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==41&&fileCallback!=null){fileCallback.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(result,data));fileCallback=null;}}
 @Override protected void onPause(){if(ready)game.evaluateJavascript("window.WorldEngineClient.save()",null);CookieManager.getInstance().flush();game.onPause();super.onPause();}
 @Override protected void onResume(){super.onResume();if(game!=null)game.onResume();}
 @Override protected void onDestroy(){if(connectivity!=null&&networkCallback!=null)connectivity.unregisterNetworkCallback(networkCallback);network.shutdownNow();CookieManager.getInstance().flush();game.destroy();super.onDestroy();}
}
