'use strict';
const $=id=>document.getElementById(id),api=window.worldEngine;let games=[],selected=null,current=null,page='library',recent=[],downloads=[];
function toast(message){$('status').textContent=message;$('status').hidden=false;setTimeout(()=>$('status').hidden=true,6000);}
async function call(action,value){try{return await api.call(action,value)}catch(error){toast(error.message.replace(/^Error invoking remote method[^:]+:\s*/,''));return null}}
function select(game){selected=game;$('detail').hidden=false;$('detail-art').src='https://worldengine.space'+game.image;$('title').textContent=game.title.replace(' - Recomplied','');$('sequence').textContent=String(games.indexOf(game)+1).padStart(2,'0');$('detail').classList.remove('changed');void $('detail').offsetWidth;$('detail').classList.add('changed');$('description').textContent=game.description;$('genre').textContent=game.genre;$('controls').textContent=game.controls;$('play').replaceChildren(document.createTextNode(current===game.id?'RESUME':'PLAY'));const arrow=document.createElement('span');arrow.textContent='↗';$('play').append(arrow);$('download').disabled=!game.download;$('download-size').textContent=game.download?`${Math.ceil(game.download.bytes/1024/1024)} MB`:'';document.querySelectorAll('.card').forEach(c=>c.classList.toggle('selected',c.dataset.id===game.id));}
function render(){const query=$('search').value.toLowerCase();let list=games.filter(g=>g.title.toLowerCase().includes(query));if(page==='recent')list=recent.flatMap(id=>list.filter(g=>g.id===id));$('cards').replaceChildren();for(const game of list){const card=document.createElement('button');card.className='card';card.dataset.id=game.id;card.setAttribute('aria-label',game.title);const img=document.createElement('img');img.src='https://worldengine.space'+game.image;img.alt='';const label=document.createElement('span');label.className='label';label.textContent=game.title.replace(' - Recomplied','');const subtitle=document.createElement('small');subtitle.textContent=String(games.indexOf(game)+1).padStart(2,'0');label.append(subtitle);card.append(img,label);if(recent[0]===game.id){const mark=document.createElement('span');mark.className='recent';mark.textContent='LAST PLAYED';card.append(mark);}card.onclick=()=>select(game);card.ondblclick=()=>play(game);$('cards').append(card);}if(list.length)select(list.find(g=>g.id===selected?.id)||list[0]);else{$('detail').hidden=true;const p=document.createElement('p');p.textContent=page==='recent'?'Games you play will appear here.':'No matching games.';$('cards').append(p)}$('summary').textContent=String(games.length).padStart(2,'0');}
async function navigate(next){if(!await call('page',next))return;page=next;$('library').hidden=!['library','recent'].includes(page);$('downloads').hidden=page!=='downloads';document.querySelectorAll('.nav[data-page]').forEach(n=>n.classList.toggle('selected',n.dataset.page===page));$('heading').textContent=page==='recent'?'Recently played':'Library';$('window-title').textContent=page==='game'?'Playing':page[0].toUpperCase()+page.slice(1);if(['library','recent'].includes(page))render();}
async function play(game=selected){if(!game)return;$('play').disabled=true;document.body.classList.add('launching');setTimeout(()=>document.body.classList.remove('launching'),600);const result=await call('play',game.id);$('play').disabled=false;if(result){current=game.id;recent=[current,...recent.filter(id=>id!==current)];$('resume').title='Resume '+game.title;$('resume').setAttribute('aria-label','Resume '+game.title);$('resume').hidden=false;$('no-game').hidden=true;$('window-title').textContent=game.title;document.querySelectorAll('.nav').forEach(n=>n.classList.remove('selected'));}}
function renderDownloads(){const container=$('download-list');container.replaceChildren();$('downloads-empty').hidden=downloads.length>0;$('download-count').textContent=downloads.filter(d=>d.state==='progressing').length||'';for(const item of downloads){const row=document.createElement('div');row.className='download-row';const info=document.createElement('div');info.className='info';const title=document.createElement('strong');title.textContent=item.title;const state=document.createElement('small');state.textContent=item.state==='completed'?'Ready to install':item.state==='progressing'?`${Math.round(item.received/1048576)} / ${Math.round(item.total/1048576)} MB` : item.state;info.append(title,state);if(item.state==='progressing'){const progress=document.createElement('progress');progress.max=item.total||1;progress.value=item.received;info.append(progress);}const action=document.createElement('button');action.textContent=item.state==='completed'?'Show in folder ↗':'Cancel';action.disabled=!['completed','progressing'].includes(item.state);action.onclick=()=>call(item.state==='completed'?'reveal':'cancel',item.id);row.append(info,action);container.append(row);}}
document.querySelectorAll('[data-page]').forEach(n=>n.onclick=()=>navigate(n.dataset.page));$('search').oninput=render;$('play').onclick=()=>play();$('resume').onclick=()=>play(games.find(g=>g.id===current));$('download').onclick=async()=>{if(await call('download',selected.id)){toast('Download started');await navigate('downloads')}};$('fullscreen').onclick=()=>call('fullscreen');$('website').onclick=()=>call('website');$('account').onclick=()=>call('account');$('open-downloads').onclick=()=>call('folder');
api.listen(event=>{if(event.type==='downloads'){downloads=event.items;renderDownloads()}if(event.type==='account')$('account-name').textContent=event.username||'Sign in';if(event.type==='error')toast(event.message)});
(async()=>{const data=await call('init');if(!data){$('connection').textContent='Offline';return}games=data.games;recent=data.recent;downloads=data.downloads;$('connection').textContent=data.offline?'Offline':'● Online';render();renderDownloads()})();

document.addEventListener('keydown',event=>{if(event.target.matches('input,textarea')||!['library','recent'].includes(page)||event.metaKey||event.ctrlKey||(!event.target.closest('#library')&&event.target!==document.body))return;const cards=[...document.querySelectorAll('.card')],index=cards.findIndex(c=>c.dataset.id===selected?.id);const step={ArrowLeft:-1,ArrowRight:1,ArrowUp:-5,ArrowDown:5}[event.key];if(step){event.preventDefault();cards[(index+step+cards.length)%cards.length]?.click();}else if(event.key==='Enter'){event.preventDefault();play();}});
// A quiet moving star map, rendered locally without a video or network dependency.
(()=>{const canvas=$('starfield'),ctx=canvas.getContext('2d'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let seed=9173;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};const stars=Array.from({length:95},()=>({x:random(),y:random(),r:.35+random()*.7,a:.12+random()*.55,phase:random()*6.28}));let width=0,height=0,last=0;function draw(time){if(time-last>60||reduced){last=time;const rect=canvas.getBoundingClientRect();if(rect.width&&rect.height){if(width!==rect.width||height!==rect.height){width=rect.width;height=rect.height;canvas.width=width*devicePixelRatio;canvas.height=height*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);}ctx.clearRect(0,0,width,height);for(const s of stars){ctx.beginPath();ctx.fillStyle=`rgba(166,210,230,${s.a*(.8+.2*Math.sin(time/4000+s.phase))})`;ctx.arc(s.x*width,s.y*height,s.r,0,Math.PI*2);ctx.fill();}}}if(!reduced)requestAnimationFrame(draw)}requestAnimationFrame(draw)})();
