const {app,BrowserWindow,WebContentsView,Menu,shell,session,ipcMain,net}=require('electron');
const path=require('node:path'),fs=require('node:fs/promises'),crypto=require('node:crypto');
const HOME='https://worldengine.space/play/';let window,engine,engineReady,engineVisible=false,current=null,catalog=[],recent=[],offline=false,closing=false;const downloads=new Map();
const platform=({win32:'windows',darwin:'mac',linux:'linux'})[process.platform];
const dataFile=()=>path.join(app.getPath('userData'),'library.json'),downloadDir=()=>path.join(app.getPath('downloads'),'WorldEngine');
function allowed(url){try{const u=new URL(url);return u.origin==='https://worldengine.space'&&(u.pathname==='/play'||u.pathname.startsWith('/play/'));}catch{return false}}
function external(url){try{if(new URL(url).protocol==='https:')shell.openExternal(url)}catch{}}
function emit(event){if(window&&!window.isDestroyed())window.webContents.send('client-event',event)}
function resize(){if(!window||!engine)return;const [w,h]=window.getContentSize();engine.setBounds({x:72,y:48,width:Math.max(1,w-72),height:Math.max(1,h-48)})}
function visible(value){engineVisible=value;engine?.setVisible(value);resize()}
async function persist(){await fs.writeFile(dataFile(),JSON.stringify({catalog,recent,downloads:[...downloads.values()].filter(d=>d.state==='completed').map(({item,...d})=>d)}))}
async function fileHash(file){const hash=crypto.createHash('sha256');for await(const chunk of require('node:fs').createReadStream(file))hash.update(chunk);return hash.digest('hex')}
function sendDownloads(){emit({type:'downloads',items:[...downloads.values()].map(({item,...d})=>d)})}
function secure(contents){contents.setWindowOpenHandler(({url})=>{external(url);return {action:'deny'}});contents.on('will-navigate',(event,url)=>{if(!allowed(url)){event.preventDefault();external(url)}});contents.on('will-attach-webview',event=>event.preventDefault());}
async function readyEngine(){if(!engineReady){engineReady=(async()=>{await engine.webContents.loadURL(HOME,{userAgent:engine.webContents.getUserAgent()+' WorldEngineClient/1.0'});for(let i=0;i<100;i++){if(await engine.webContents.executeJavaScript('Boolean(window.WorldEngineClient?.ready())'))return;await new Promise(r=>setTimeout(r,200));}throw Error('The library service did not respond. Check your internet connection.');})().catch(error=>{engineReady=null;throw error})}return engineReady}
async function engineCall(method,value){await readyEngine();return engine.webContents.executeJavaScript(`window.WorldEngineClient.${method}(${value===undefined?'':JSON.stringify(value)})`)}
async function initialize(){try{const saved=JSON.parse(await fs.readFile(dataFile(),'utf8'));catalog=saved.catalog||[];recent=saved.recent||[];for(const item of saved.downloads||[])downloads.set(item.id,item)}catch{}try{const response=await net.fetch(HOME+'games.json');if(!response.ok)throw Error('Library unavailable');const data=await response.json();if(!Array.isArray(data)||data.some(g=>!/^[a-z0-9-]+$/.test(g.id)))throw Error('Invalid library');catalog=data;await persist()}catch{offline=true}return {games:catalog.map(g=>({...g,download:g.downloads?.[platform]||null})),recent,offline,downloads:[...downloads.values()].map(({item,...d})=>d)}}
async function command(event,action,value){if(event.sender!==window.webContents||event.senderFrame!==window.webContents.mainFrame)throw Error('Untrusted client command');switch(action){
case 'init':return initialize();
case 'play':{const game=catalog.find(g=>g.id===value);if(!game)throw Error('Unknown game');await engineCall('launch',value);current=value;visible(true);recent=[value,...recent.filter(id=>id!==value)].slice(0,10);await persist();return true;}
case 'page':if(!['library','recent','downloads','wishlist'].includes(value))throw Error('Unknown page');if(value==='wishlist'){await engineCall('wishlist');visible(true)}else{if(engineReady)await engineCall('save');visible(false)}return true;
case 'account':await readyEngine();visible(true);await engineCall('account');return true;
case 'fullscreen':window.setFullScreen(!window.isFullScreen());return true;
case 'website':external('https://worldengine.space');return true;
case 'folder':await fs.mkdir(downloadDir(),{recursive:true});await shell.openPath(downloadDir());return true;
case 'reveal':{const d=downloads.get(value);if(d?.state==='completed')shell.showItemInFolder(d.path);return true;}
case 'cancel':downloads.get(value)?.item?.cancel();return true;
case 'download':{const game=catalog.find(g=>g.id===value),asset=game?.downloads?.[platform];if(!asset||!/^https:\/\/github\.com\/worldengine-space\/game-downloads\/releases\/download\/[a-zA-Z0-9._/-]+$/.test(asset.url)||!/^[a-zA-Z0-9._-]+$/.test(asset.filename)||!/^[a-f0-9]{64}$/.test(asset.sha256))throw Error('No installer available for this platform');if([...downloads.values()].some(d=>d.game===value&&d.state==='progressing'))return true;await fs.mkdir(downloadDir(),{recursive:true});const id=crypto.randomUUID();downloads.set(id,{id,game:value,title:game.title,url:asset.url,path:path.join(downloadDir(),asset.filename),sha256:asset.sha256,total:asset.bytes,received:0,state:'progressing'});session.fromPartition('persist:worldengine-client').downloadURL(asset.url);sendDownloads();return true;}
default:throw Error('Unknown client command');}}
if(!app.requestSingleInstanceLock())app.quit();
app.whenReady().then(()=>{window=new BrowserWindow({title:'WorldEngine.space',width:1360,height:900,minWidth:960,minHeight:600,backgroundColor:'#12161c',icon:path.join(__dirname,'icon.png'),webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});engine=new WebContentsView({webPreferences:{nodeIntegration:false,contextIsolation:true,sandbox:true,partition:'persist:worldengine-client'}});window.contentView.addChildView(engine);engine.webContents.loadURL("about:blank");visible(false);secure(engine.webContents);window.webContents.setWindowOpenHandler(()=>({action:'deny'}));window.webContents.on('will-navigate',e=>e.preventDefault());window.on('resize',resize);window.loadFile(path.join(__dirname,'client.html'));ipcMain.handle('client-command',command);
const s=session.fromPartition('persist:worldengine-client');s.setPermissionRequestHandler((_contents,permission,callback)=>callback(permission==='fullscreen'));s.on('will-download',(_event,item)=>{const entry=[...downloads.values()].find(d=>d.state==='progressing'&&!d.item&&item.getURLChain().includes(d.url));if(!entry)return;entry.item=item;item.setSavePath(entry.path);item.on('updated',()=>{entry.received=item.getReceivedBytes();entry.total=item.getTotalBytes();sendDownloads()});item.once('done',async(_event,state)=>{entry.state=state;if(state==='completed'){entry.state='Verifying';sendDownloads();try{const hash=await fileHash(entry.path);if(hash!==entry.sha256){entry.state='Verification failed';await fs.rm(entry.path,{force:true})}else entry.state='completed'}catch{entry.state='Verification failed'}}delete entry.item;sendDownloads();await persist()})});
setInterval(async()=>{if(engineReady&&engineVisible)try{const state=await engineCall('state');emit({type:'account',username:state.username})}catch{}},3000).unref();
window.on('close',event=>{if(closing)return;event.preventDefault();closing=true;Promise.race([engineReady?engineCall('save'):Promise.resolve(),new Promise(r=>setTimeout(r,4000))]).catch(()=>{}).finally(()=>{engine.webContents.close();window.destroy();app.quit()})});Menu.setApplicationMenu(Menu.buildFromTemplate([{label:'World Engine',submenu:[{label:'Library',accelerator:'CmdOrCtrl+L',click:()=>visible(false)},{label:'Fullscreen',accelerator:'F11',click:()=>window.setFullScreen(!window.isFullScreen())},{type:'separator'},{role:'quit'}]},{role:'editMenu'}]));});
app.on('second-instance',()=>{window?.show();window?.focus()});app.on('window-all-closed',()=>app.quit());
